### ISSUE TITLE
App does not work 

### ISSUE THREAD

**Issue by PiLemichel** [ullalaaron/angular-peerjs#5]
Hi,
Obviously the app does not work anymore, when we try to join nothing happens. same on https://angular-peerjs.vercel.app/
or when you launch the app locally. the code would be obsolete since a new version?

Thks for your Medium.

**Comment by ullalaaron** [comment]
Hi @PiLemichel !
Thanks for your comment.
Are you using two different sessions to start the call and to join the call (one tab needs to be opened in incognito). 
I'll try to figure out if there are any errors or if it's network related.

**Comment by PiLemichel** [comment]
@ullalaaron thks for your response :)
